### ISSUE TITLE
Tic Tac Toe 

### ISSUE THREAD

**Issue by mrsgoranson** [DubuqueSeniorCS/Personal-Projects#1]
This is great! 
I am wanting to use this for the demo at the Foundation Dinner....do you have the latest version uploaded? I can play...and win but I can only play once. Is that what it is supposed to do? Let me know or I will check in with you during 3rd hour. 

Awesome Work!

**Comment by HaylockGrant** [comment]
Tic Tac Toe is now bootable without the need of a desktop environment or a windows for key input.
